config/routes.rb
Rails.application.routes.draw do
  resources :friends
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  def index
    @friends = Friend.all
  end

  def show
  end

  def new
    @friend = Friend.new
  end

  def edit
  end

  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        #format.html { redirect_to friend_url(@friend), notice: "CREADO" }
        format.html { redirect_to friends_path}
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Actualizado correctamente." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private

    def set_friend
      @friend = Friend.find(params[:id])
    end

    def friend_params
      params.require(:friend).permit(:name, :surname, :address, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> No se puede guardar:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">

                 
                  
                  <div class="form-group field">
                    <%= form.label :name, class: "h3" %><br>
                    <%= form.text_field :name,  class: "form-control mb-2 mr-sm-2 mb-sm-0" %>
                  </div>

                  <div class="form-group field">
                    <%= form.label :surname, class: "h3" %><br>
                    <%= form.text_field :surname,  class: "form-control mb-2 mr-sm-2 mb-sm-0" %>
                  </div>

                  <div class="form-group field">
                    <%= form.label :address, class: "h3" %><br>
                    <%= form.text_field :address,  class: "form-control mb-2 mr-sm-2 mb-sm-0" %>
                  </div>

                   <div class="form-group field">
                    <%= form.label :date_of_birth, class: "h3" %><br>
                    <%= form.date_select :date_of_birth,  class: "form-control mb-2 mr-sm-2 mb-sm-0" %>
                  </div>

  

               

                  <div class="actions" >
                   <%= button_tag(type: 'submit', class: "btn btn-primary") do %> <i class="icon-ok icon-white"></i> Guardar <% end %>
                  </div>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Nombre:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= friend.surname %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= friend.addres %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1></h1>
<h1 class="text-center">Editar</h1>

<%= render 'form', friend: @friend %>



<h2 class="text-center">
<%= link_to friends_path do %> <button type="button" class="btn btn-outline-danger"> <i class="bi bi-skip-backward"></i> Atras</button> <% end %>

</h2>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container-sm">


<h1 class="text-center">Amigos CRUD</h1>

<table class="table align-middle mb-0 bg-white">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Direccion</th>
      <th>F. Nacimiento</th>
      
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.surname %></td>
        <td><%= friend.address %></td>
        <td><%= friend.date_of_birth %></td>
        <td><%= link_to friend do %> <button type="button" class="btn btn-primary"> <i class="bi bi-eye"></i> </button> <% end %></td>
        <td><%= link_to edit_friend_path(friend) do %> <button type="button" class="btn btn-warning"> <i class="bi bi-pencil-square"></i> </button> <% end %></td>
        <td> <%= link_to friend, method: :delete, data: { confirm: '¿Estas seguro?' } do %> <button type="button" class="btn btn-danger"> <i class="bbi bi-trash3"></i> </button><% end %> </td>

      </tr>
    <% end %>
  </tbody>
</table>


<br>
<%= link_to new_friend_path do %> <button type="button" class="btn btn-outline-primary"> <i class="bi bi-person-plus"></i> Nuevo Amigo </button> <% end %>

</div>

app/views/friends/new.html.erb
<h1></h1>
<h1 class="text-center">Nuevo amigo</h1>

<%= render 'form', friend: @friend %>
<br>
<p class="text-center">
            <%= link_to friends_path do %> <button type="button" class="btn btn-outline-danger"> <i class="bi bi-skip-backward"></i> Atras</button> <% end %>


</p>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-sm">


<h1 class="text-center">Amigos CRUD | VER</h1>

<table class="table align-middle mb-0 bg-white">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Direccion</th>
      <th>F. Nacimiento</th>
      
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td><%= @friend.name %></td>
        <td><%= @friend.surname %></td>
        <td><%= @friend.address %></td>
        <td><%= @friend.date_of_birth %></td>
      </tr>
  </tbody>
</table>
<br>
<%= link_to edit_friend_path(@friend) do %> <button type="button" class="btn btn-outline-primary"> <i class="bi bi-pencil-square"></i> Editar</button> <% end %>
        <br>
        <br>
        <%= link_to friends_path do %> <button type="button" class="btn btn-outline-danger"> <i class="bi bi-skip-backward"></i> Atras</button> <% end %>
</div>

      </div>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>